---
include:
  - project: devopsworks/templates/gitlab-ci
    file: code/golang.yml
  - project: devopsworks/templates/gitlab-ci
    file: code/generic.yml
  - project: devopsworks/templates/gitlab-ci
    file: docker/generic.yml
  # - template: Code-Quality.gitlab-ci.yml this is broken
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

image: golang:1.14

cache:
  paths:
    - .cache

variables:
  GOPATH: "$CI_PROJECT_DIR/.cache"

stages:
  - lint
  - test
  - build
  - scan
  - publish

go:cilint:
  extends: .golang_cilint
  stage: lint

go:vet:
  extends: .golang_vet
  stage: lint

docker:lint:
  extends: .docker_lint
  stage: lint

go:test:
  extends: .golang_test
  stage: test

go:gen:sast:
  extends: .code_sast
  stage: test

go:coverage:
  extends: .golang_coverage
  stage: test

go:gen:depscan:
  extends: .code_depscan
  stage: test

go:docker:
  extends: .golang_docker_build
  stage: build

go:build:
  stage: build
  script:
    - make release
  artifacts:
    paths:
      - ./bin/*
    expire_in: 1 week

# Does not work nor it's necessary with scratch images
# docker:scan:
#   stage: scan
#   extends: .docker_scan_trivy

release:publish:
  stage: publish
  image: python3
  before_script:
    - pip3 install gitlab-release
  script:
    - gitlab-release --link-artifact ./bin/*
  artifacts:
    paths:
      - ./bin/*
    expire_in: 1 week
  only:
    - tags