---
image: golang:1.14

variables:
  GOCACHE: "off"

stages:
  - test
  - build

go:tests:
  stage: test
  script:
    - make test

go:race:
  stage: test
  script:
    - make test-race

go:coverage:
  stage: test
  script:
    - make test-coverage

go:lint:
  stage: test
  script:
    - make lint

go:build:
  stage: build
  script:
    - make
