name: Benchmarks
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Benchmark
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v . -run=__absolutelynothing__ -bench=.